---
format: pdf
---

# Report Guidelines

\begin{tabular}{|ll}
&    \underline{Classical Time Series Modelling (Unit 1) }  \\[5pt]
      & 1. \; Identify/model long-term trends (polynomial regression, smoothing, etc.)
\\    & 2. \; Identify/model seasonal components (harmonic regression, differencing, etc.)
\\    & 3. \; Determine whether residuals are uncorrelated over time, via the sample ACF
\\[15pt]
&    \underline{Linear Filters and ARMA(p,q) processes (Unit 2) }  \\[5pt]
      & Identify ARMA behaviour in the residuals by examining their sample ACF, 
\\    & and/or using more quantified diagnostics such as AIC.
\\[15pt]
&    \underline{Linear Prediction and Forecasting (Unit 3)}  \\[5pt]
      & 1. \; Partition the data into training (past) and testing (future) intervals. 
\\    & 2. \; Evaluate the training model's forecasting abilities by comparing its prediction  
\\    &    \;\, \quad (and 95\% CI) to the testing data.
\\    & 3. \; Forecast some length of time into the future, using the full dataset, and plot.
\\[15pt]
&     \underline{Theory + Interpretation}  \\[5pt]
      & 1. \; Was the students model able to effectively capture the data's behaviour?
\\    &    \;\, \quad If not, what were the main barriers? (non-stationarity, missing data, etc.)
\\    & 2. \; Were the student's hypotheses supported by the model? 
\\    & 3. \; What scientific conclusions can be made about the data, given the final model?  
\end{tabular}

---

# What do you think?

#### Regarding subsets of the data
You can use any portion of your chosen dataset, as long as the portion in question is at least $N\approx 50$ observations long. 

#### Formatting!
1.    It must be a rendered Quarto document (PDF not HTML)
2.    Plotting Ettiquette
3.    Latex! alpha = 0.05

$$
X_t = m_t + s_t + Y_t
$$

The MA(1) parameter is $\theta = 0.17$. This was found using... 
#### Teamwork Strategy
Give it to me again! It may not match your originally proposed plan.

#### 2-player mode
Both series ($X_t,Y_t$) must be modelled according to methods from Units 1,2 and 3, if relevant.


$$
X_t - \phi_1 X_{t-1} = Z_t + \theta_1 Z_{t-1} + \theta_2 Z_{t-2}
$$

$$
\sum_{i=1}^\infty
$$



$$
\begin{aligned}
    \begin{bmatrix}
      1 & 2 \\ 
      3 & 4
    \end{bmatrix}
    &= 
    \begin{bmatrix}
      1 & 2 \\ 
      3 & 4
    \end{bmatrix}
    \\
    \begin{bmatrix}
      1 & 2 \\ 
      3 & 4
    \end{bmatrix}
    &= 
    \begin{bmatrix}
      1 & 2 \\ 
      3 & 4
    \end{bmatrix}
\end{aligned}
$$










